// ============================================================
// IPMS 流程视图 — 数据层
// ============================================================

const STAGES = [
  { id: 'gr1',  code: 'GR1',  name: '规划与立项', ipdGate: 'Charter → CDCP' },
  { id: 'gr2',  code: 'GR2',  name: '拓展准备',   ipdGate: 'CDCP → PDCP' },
  { id: 'gr3',  code: 'GR3',  name: '市场拓展',   ipdGate: 'PDCP → 开发验证' },
  { id: 'gr4',  code: 'GR4',  name: '上市准备',   ipdGate: '开发验证 → ADCP' },
  { id: 'gr5',  code: 'GR5',  name: '上市销售',   ipdGate: 'ADCP → 发布' },
  { id: 'gr5a', code: 'GR5A', name: '稳定销售',   ipdGate: '发布持续期' },
  { id: 'gr6',  code: 'GR6',  name: '退市撤盘',   ipdGate: '→ EOX' },
];

// IPD 阶段带（按列索引映射，startIdx/endIdx 对应 STAGES 数组下标）
const IPD_PHASES = [
  { name: '概念阶段',       startIdx: 0, endIdx: 0, color: '#dbeafe', accent: '#2563eb', gate: 'CDCP' },
  { name: '计划阶段',       startIdx: 1, endIdx: 1, color: '#ede9fe', accent: '#7c3aed', gate: 'PDCP' },
  { name: '开发和验证阶段', startIdx: 2, endIdx: 3, color: '#fce7f3', accent: '#db2777', gate: 'ADCP' },
  { name: '发布阶段',       startIdx: 4, endIdx: 4, color: '#dcfce7', accent: '#16a34a', gate: '' },
  { name: '生命周期管理',   startIdx: 5, endIdx: 6, color: '#fef9c3', accent: '#ca8a04', gate: 'EOX' },
];

// PDT 顶层管理层（图片顶部的四个管理维度）
const IPD_MANAGEMENT = [
  { name: '管理 Offering 与组合', span: 2 },
  { name: '管理 Idea',            span: 1 },
  { name: '管理研发',             span: 2 },
  { name: '管理产品数据',         span: 2 },
];

// ============================================================
// PDT — 产品开发团队
// ============================================================
const PDT_ROLES = [
  {
    id: 'lpdt',
    role: 'LPDT',
    title: '项目发起人',
    subtitle: '产品经理 / 事业部项目经理',
    color: '#1d4ed8',
    stages: {
      gr1:  { deliverables: ['Charter 文件', '立项申请书', '产品战略方向', 'IPMT 回顾材料'], models: ['商业模式画布', 'SWOT分析'] },
      gr2:  { deliverables: ['产品规格书 (PRD)', 'CDCP 评审材料', '产品路线图初版', '技术方案确认'], models: ['价值主张画布'] },
      gr3:  { deliverables: ['开发里程碑计划', '设计评审报告', 'PDCP 评审材料'], models: [] },
      gr4:  { deliverables: ['Beta 测试报告', 'ADCP 评审材料', '产品验收标准'], models: [] },
      gr5:  { deliverables: ['产品发布包', 'GTM 确认文件', '上市授权'], models: [] },
      gr5a: { deliverables: ['版本迭代路线图', '产品优化计划'], models: ['BCG矩阵'] },
      gr6:  { deliverables: ['EOX 通知', '退市计划', '产品下线时间表'], models: [] },
    },
  },
  {
    id: 'market',
    role: '市场代表',
    title: '市场代表',
    subtitle: '产品市场经理',
    color: '#0891b2',
    stages: {
      gr1:  { deliverables: ['市场调研报告', '竞品分析矩阵', '用户画像 (Persona)', '市场规模 (TAM/SAM/SOM)'], models: ['SWOT分析', '波特五力模型', 'PEST分析', '用户画像(Persona)', '卡诺模型(Kano)'] },
      gr2:  { deliverables: ['产品定位文档', 'USP 定义', '价值主张', '定价策略框架'], models: ['STP策略', '价值主张画布'] },
      gr3:  { deliverables: ['产品卖点文案 (FABE)', '物化文案', '产品命名方案', 'TR 评审材料'], models: ['FABE模型'] },
      gr4:  { deliverables: ['上市营销方案', '媒体物料清单', '市场计划确认'], models: ['4P营销组合'] },
      gr5:  { deliverables: ['营销效果追踪报告', '销售赋能材料', '市场活动复盘'], models: [] },
      gr5a: { deliverables: ['市场复盘报告', '竞品动态更新', '产品优化建议'], models: [] },
      gr6:  { deliverables: ['退市沟通方案', '替代产品推荐'], models: [] },
    },
  },
  {
    id: 'procurement',
    role: '采购代表',
    title: '采购代表',
    subtitle: '采购工程师 / 供应商经理',
    color: '#065f46',
    stages: {
      gr1:  { deliverables: ['BOM 初版', '关键物料评估', '供应商初步调研'], models: [] },
      gr2:  { deliverables: ['供应商短名单', '报价对比表', '交期评估'], models: [] },
      gr3:  { deliverables: ['物料认证报告', '交期锁定计划', '供应链风险评估'], models: [] },
      gr4:  { deliverables: ['量产备货计划', '供应商协议签署', 'BOM 成本锁定'], models: [] },
      gr5:  { deliverables: ['持续供货保障', '备货状态报告'], models: [] },
      gr5a: { deliverables: ['库存优化方案', '安全库存策略'], models: [] },
      gr6:  { deliverables: ['停产物料清单', '余料处置方案'], models: [] },
    },
  },
  {
    id: 'manufacturing',
    role: '制造代表',
    title: '制造代表',
    subtitle: '工艺工程师 / 生产经理',
    color: '#6d28d9',
    stages: {
      gr1:  { deliverables: ['制造可行性评估', '产线方案初稿'], models: [] },
      gr2:  { deliverables: ['工艺方案设计', 'DFM 报告 (可制造性设计)'], models: [] },
      gr3:  { deliverables: ['EVT 试产报告', 'DVT 试产报告', '产线搭建方案'], models: [] },
      gr4:  { deliverables: ['PVT 量产验证报告', '产能评估', 'PCBA 验收'], models: [] },
      gr5:  { deliverables: ['量产爬坡计划', '产能保障报告'], models: [] },
      gr5a: { deliverables: ['生产优化报告', '良率提升方案'], models: [] },
      gr6:  { deliverables: ['产线停产安排', '设备处置计划'], models: [] },
    },
  },
  {
    id: 'quality',
    role: '质量代表',
    title: '质量代表',
    subtitle: '质量工程师 / QA 经理',
    color: '#b45309',
    stages: {
      gr1:  { deliverables: ['质量目标定义', '质量标准框架'], models: ['FMEA'] },
      gr2:  { deliverables: ['测试计划', '可靠性测试方案'], models: [] },
      gr3:  { deliverables: ['EVT 测试报告', 'DVT 测试报告', '问题跟踪清单'], models: ['6-Sigma'] },
      gr4:  { deliverables: ['可靠性认证 (ODC)', 'PCCE 认证', '出货检验标准'], models: [] },
      gr5:  { deliverables: ['出货检验报告', '品质监控计划'], models: [] },
      gr5a: { deliverables: ['市场质量反馈报告', '品质预警机制'], models: [] },
      gr6:  { deliverables: ['质量档案归档', '质量总结报告'], models: [] },
    },
  },
  {
    id: 'finance',
    role: '财务代表',
    title: '财务代表',
    subtitle: '财务分析师 / FP&A',
    color: '#9d174d',
    stages: {
      gr1:  { deliverables: ['商业计划书', '投资回报预测 (ROI)', '财务可行性评估'], models: ['ROI分析', 'P&L模型'] },
      gr2:  { deliverables: ['BOM 成本核算', '目标成本设定', '成本结构分析'], models: ['BOM成本分析'] },
      gr3:  { deliverables: ['成本跟踪报告', '偏差分析'], models: [] },
      gr4:  { deliverables: ['P&L 预测', '定价方案', '盈亏平衡分析'], models: [] },
      gr5:  { deliverables: ['销售核算', '毛利分析报告', '财务实绩 vs 预测'], models: [] },
      gr5a: { deliverables: ['财务复盘报告', '预测调整'], models: [] },
      gr6:  { deliverables: ['产品结算报告', '资产处置方案'], models: [] },
    },
  },
  {
    id: 'service_tech',
    role: '技术服务代表',
    title: '技术服务代表',
    subtitle: '售后工程师 / 服务经理',
    color: '#0f766e',
    stages: {
      gr1:  { deliverables: ['售后策略初稿', '服务模式评估'], models: [] },
      gr2:  { deliverables: ['维修手册', '备件清单', '服务网络规划'], models: [] },
      gr3:  { deliverables: ['服务培训材料', '维修流程文档'], models: [] },
      gr4:  { deliverables: ['FAQ 文档', '服务流程确认', '配件供应计划'], models: [] },
      gr5:  { deliverables: ['售后服务启动', '服务热线开通'], models: [] },
      gr5a: { deliverables: ['客诉分析报告', '服务优化方案'], models: ['NPS净推荐值'] },
      gr6:  { deliverables: ['服务下线方案', '历史维修数据归档'], models: [] },
    },
  },
  {
    id: 'mo_pdt',
    role: 'MO 营运运作',
    title: 'MO 营运运作',
    subtitle: '项目管理顾问 / PMM',
    color: '#c2410c',
    isHighlight: true,
    stages: {
      gr1:  { deliverables: ['项目启动文件', 'IPD 流程对齐', '团队组建确认'], models: ['RACI矩阵'] },
      gr2:  { deliverables: ['里程碑计划', '跨部门协作机制'], models: [] },
      gr3:  { deliverables: ['跨部门协调', '风险管理报告', '进度看护'], models: ['风险矩阵'] },
      gr4:  { deliverables: ['GR4 评审组织', '评审材料汇总'], models: [] },
      gr5:  { deliverables: ['上市协调', 'GR5 评审组织'], models: [] },
      gr5a: { deliverables: ['运营复盘会议', '持续改进跟踪'], models: [] },
      gr6:  { deliverables: ['项目收尾', 'GR6 评审组织'], models: [] },
    },
  },
  {
    id: 'pmo',
    role: 'PDT / PMO',
    title: 'PDT / PMO',
    subtitle: '项目管理专员',
    color: '#475569',
    stages: {
      gr1:  { deliverables: ['项目章程', '会议纪要', '项目计划书'], models: ['WBS工作分解'] },
      gr2:  { deliverables: ['WBS 分解', '风险登记表', '沟通计划'], models: [] },
      gr3:  { deliverables: ['进度周报', '问题跟踪表', '变更管理记录'], models: [] },
      gr4:  { deliverables: ['GR 材料汇总', '评审记录'], models: [] },
      gr5:  { deliverables: ['发布协调记录', '上线检查清单'], models: [] },
      gr5a: { deliverables: ['项目状态报告', '经验教训记录'], models: [] },
      gr6:  { deliverables: ['项目总结报告', '档案归档'], models: [] },
    },
  },
];

// ============================================================
// PCT — 产品商业化团队
// ============================================================
const PCT_ROLES = [
  {
    id: 'gtm_lead',
    role: 'GTM Lead',
    title: 'GTM Lead',
    subtitle: 'GTM 经理 / 产品营销经理',
    color: '#0ea5e9',
    stages: {
      gr1:  { deliverables: ['GTM 战略框架', '市场机会评估', '商业化可行性报告'], models: ['SWOT分析', 'Ansoff矩阵'] },
      gr2:  { deliverables: ['GTM Plan', '上市路径规划', 'GR2 评审材料'], models: ['4P营销组合', 'STP策略'] },
      gr3:  { deliverables: ['市场拓展策略', '渠道优先级规划', 'GR3 评审材料'], models: [] },
      gr4:  { deliverables: ['发布计划确认', 'GR4 评审材料', '上市授权申请'], models: [] },
      gr5:  { deliverables: ['上市执行总协调', 'GR5 评审材料', '上市效果追踪'], models: [] },
      gr5a: { deliverables: ['增长策略复盘', 'GTM 调优方案'], models: [] },
      gr6:  { deliverables: ['退市 GTM 收尾', 'GR6 评审材料'], models: [] },
    },
  },
  {
    id: 'mo_pct',
    role: 'MO 营运运作',
    title: 'MO 营运运作',
    subtitle: '产品管理顾问 / PMM',
    color: '#c2410c',
    isHighlight: true,
    stages: {
      gr1:  { deliverables: ['PCT 团队组建', 'IPMS 流程对齐'], models: ['RACI矩阵'] },
      gr2:  { deliverables: ['商务流落实计划', '跨部门协作机制'], models: [] },
      gr3:  { deliverables: ['市场拓展进度管理', '问题协调'], models: [] },
      gr4:  { deliverables: ['GR4 PCT 材料整合', '上市就绪检查'], models: [] },
      gr5:  { deliverables: ['上市协调执行', 'GR5 评审支持'], models: [] },
      gr5a: { deliverables: ['运营复盘推动', '持续改进'], models: [] },
      gr6:  { deliverables: ['PCT 项目收尾', 'GR6 支持'], models: [] },
    },
  },
  {
    id: 'marketing',
    role: '营销代表',
    title: '营销代表',
    subtitle: '品牌经理 / 营销经理',
    color: '#7c3aed',
    stages: {
      gr1:  { deliverables: ['品牌策略初定', '目标受众定义'], models: ['品牌金字塔'] },
      gr2:  { deliverables: ['营销预算规划', '年度营销日历'], models: [] },
      gr3:  { deliverables: ['Campaign 策划', 'KV 视觉方案', '社交媒体策略'], models: ['A/B测试框架'] },
      gr4:  { deliverables: ['上市 Campaign 方案', '媒体投放计划'], models: [] },
      gr5:  { deliverables: ['营销活动执行报告', '效果数据追踪'], models: ['AARRR海盗模型'] },
      gr5a: { deliverables: ['促销策略', '季节性活动规划'], models: [] },
      gr6:  { deliverables: ['停售通知', '库存清仓营销'], models: [] },
    },
  },
  {
    id: 'content',
    role: '内容与创意',
    title: '内容与创意',
    subtitle: '内容主管 / 创意设计师',
    color: '#be185d',
    stages: {
      gr1:  { deliverables: ['品牌调性指南', 'VI 规范初版'], models: [] },
      gr2:  { deliverables: ['物料规划清单', '创意方向确认'], models: [] },
      gr3:  { deliverables: ['核心 KV', '产品视频', '电商详情页设计'], models: [] },
      gr4:  { deliverables: ['全套上市物料', 'Banner 素材', '包装设计终稿'], models: [] },
      gr5:  { deliverables: ['日常内容运营', 'SNS 素材更新'], models: [] },
      gr5a: { deliverables: ['内容优化迭代', 'A/B 素材测试'], models: [] },
      gr6:  { deliverables: ['下线内容处理', '物料档案整理'], models: [] },
    },
  },
  {
    id: 'retail',
    role: '零售代表',
    title: '零售代表',
    subtitle: '零售运营经理',
    color: '#0f766e',
    stages: {
      gr1:  { deliverables: ['零售渠道评估', '门店优先级规划'], models: [] },
      gr2:  { deliverables: ['门店方案规划', '陈列策略'], models: [] },
      gr3:  { deliverables: ['终端陈列方案', 'POP 素材', '线下体验店方案'], models: [] },
      gr4:  { deliverables: ['零售培训材料', '门店备货计划', 'POSM 物料'], models: [] },
      gr5:  { deliverables: ['门店上架报告', '线下活动执行', '零售数据追踪'], models: [] },
      gr5a: { deliverables: ['零售数据分析', '陈列优化方案'], models: [] },
      gr6:  { deliverables: ['门店下架方案', '库存清仓协调'], models: [] },
    },
  },
  {
    id: 'ecommerce',
    role: '渠道/电商代表',
    title: '渠道/电商代表',
    subtitle: '电商运营经理 / 渠道经理',
    color: '#b45309',
    stages: {
      gr1:  { deliverables: ['电商渠道策略', '平台选择评估'], models: [] },
      gr2:  { deliverables: ['平台合作方案', '仓配方案', '首发平台确认'], models: [] },
      gr3:  { deliverables: ['电商详情页', '促销方案', '定价策略配合'], models: [] },
      gr4:  { deliverables: ['首发方案', '预售策略', '活动报名确认'], models: [] },
      gr5:  { deliverables: ['平台首发执行', '大促 GMV 追踪', '仓配状态报告'], models: [] },
      gr5a: { deliverables: ['日销运营报告', '平台活动规划', 'Listing 优化'], models: [] },
      gr6:  { deliverables: ['平台下架处理', '库存消化方案'], models: [] },
    },
  },
  {
    id: 'pr_kol',
    role: 'PR / KOL 代表',
    title: 'PR / KOL 代表',
    subtitle: '公关经理 / KOL 经理',
    color: '#1d4ed8',
    stages: {
      gr1:  { deliverables: ['PR 策略规划', '媒体资源梳理'], models: [] },
      gr2:  { deliverables: ['KOL 矩阵规划', '媒体合作洽谈'], models: [] },
      gr3:  { deliverables: ['KOL Brief', '内容共创方案', '媒体预热计划'], models: [] },
      gr4:  { deliverables: ['发布会策划', 'PR 稿件', '媒体邀请名单'], models: [] },
      gr5:  { deliverables: ['发布会执行', '媒体报道追踪', 'KOL 内容上线'], models: [] },
      gr5a: { deliverables: ['持续 KOL 合作', '口碑监控报告'], models: [] },
      gr6:  { deliverables: ['停售 PR 沟通', '媒体通知发布'], models: [] },
    },
  },
  {
    id: 'crm',
    role: 'CRM / 用户运营',
    title: 'CRM / 用户运营',
    subtitle: 'CRM 经理 / 用户产品经理',
    color: '#9d174d',
    stages: {
      gr1:  { deliverables: ['用户运营策略', '目标用户群定义'], models: ['用户画像(Persona)', 'RFM模型'] },
      gr2:  { deliverables: ['预购/Deposit 策略', '会员权益设计', 'EDM 框架'], models: [] },
      gr3:  { deliverables: ['用户获客方案', '预热社群运营'], models: [] },
      gr4:  { deliverables: ['预售/预购上线', '首发会员权益'], models: [] },
      gr5:  { deliverables: ['用户激活计划', 'EDM 营销执行', '首购数据追踪'], models: ['AARRR海盗模型'] },
      gr5a: { deliverables: ['留存 & 复购策略', '会员成长体系'], models: ['RFM模型', 'NPS净推荐值'] },
      gr6:  { deliverables: ['用户迁移通知', '会员权益调整'], models: [] },
    },
  },
  {
    id: 'sales',
    role: '销售代表',
    title: '销售代表',
    subtitle: '区域销售经理',
    color: '#065f46',
    stages: {
      gr1:  { deliverables: ['销售目标规划', '区域市场评估'], models: [] },
      gr2:  { deliverables: ['渠道规划', 'Listing 策略', '经销商方案'], models: [] },
      gr3:  { deliverables: ['销售培训材料', '销售工具包'], models: [] },
      gr4:  { deliverables: ['销售政策', '激励方案', '销售预测'], models: [] },
      gr5:  { deliverables: ['销售启动报告', '数据追踪看板', '一线反馈收集'], models: [] },
      gr5a: { deliverables: ['销售优化方案', 'Listing 激活报告'], models: [] },
      gr6:  { deliverables: ['清仓策略', '停售处理方案'], models: [] },
    },
  },
  {
    id: 'cs',
    role: '服务代表',
    title: '服务代表',
    subtitle: '客服经理',
    color: '#475569',
    stages: {
      gr1:  { deliverables: ['客服策略初定', '服务标准制定'], models: [] },
      gr2:  { deliverables: ['FAQ 框架', '服务知识库规划', '客服培训计划'], models: [] },
      gr3:  { deliverables: ['客服培训材料', '应答脚本'], models: [] },
      gr4:  { deliverables: ['服务流程测试', '客服系统配置'], models: [] },
      gr5:  { deliverables: ['客服上线报告', '问题处理追踪'], models: ['NPS净推荐值'] },
      gr5a: { deliverables: ['服务优化报告', 'CSAT 满意度提升'], models: [] },
      gr6:  { deliverables: ['服务下线方案', '历史工单归档'], models: [] },
    },
  },
];

// ============================================================
// 方法论模型库
// ============================================================
const CATEGORIES = [
  { id: 'all',         name: '全部' },
  { id: 'market',     name: '市场分析' },
  { id: 'user',       name: '用户研究' },
  { id: 'product',    name: '产品策略' },
  { id: 'gtm',        name: 'GTM & 营销' },
  { id: 'pm',         name: '项目管理' },
  { id: 'finance',    name: '财务分析' },
  { id: 'growth',     name: '用户增长' },
  { id: 'quality',    name: '质量管理' },
];

const MODELS = [
  // ── 市场分析 ──────────────────────────────────────────────
  {
    id: 'swot',
    name: 'SWOT 分析',
    nameEn: 'SWOT Analysis',
    category: 'market',
    stages: ['gr1', 'gr2'],
    departments: ['市场代表', 'GTM Lead', 'LPDT'],
    description: '从优势 (Strengths)、劣势 (Weaknesses)、机会 (Opportunities)、威胁 (Threats) 四个维度评估企业或产品的内外部竞争态势，是战略规划的基础工具。',
    howToUse: '在产品立项和定位阶段使用，帮助团队系统性识别市场机会和风险，为产品战略方向提供依据。',
    example: '新品立项时，通过 SWOT 评估竞品优劣势与市场空白，确定差异化切入点。',
    tags: ['竞争分析', '战略规划', '立项必备'],
  },
  {
    id: 'porter5',
    name: '波特五力模型',
    nameEn: "Porter's Five Forces",
    category: 'market',
    stages: ['gr1'],
    departments: ['市场代表', 'GTM Lead'],
    description: '通过分析行业竞争者、潜在进入者、替代品、供应商议价力、买方议价力五个维度，判断行业吸引力与竞争强度。',
    howToUse: '进入新市场或评估产品机会时使用，帮助判断市场进入门槛和盈利潜力。',
    example: '评估进入智能家居市场的可行性时，分析现有竞争格局与进入壁垒。',
    tags: ['行业分析', '竞争格局', '市场进入'],
  },
  {
    id: 'pest',
    name: 'PEST 分析',
    nameEn: 'PEST Analysis',
    category: 'market',
    stages: ['gr1'],
    departments: ['市场代表', 'GTM Lead'],
    description: '从政治 (Political)、经济 (Economic)、社会 (Social)、技术 (Technological) 四个宏观维度扫描外部环境，识别长期趋势与风险。',
    howToUse: '在战略规划和市场进入评估阶段使用，尤其适合新市场或新品类的机会评估。',
    example: '进入海外市场前，通过 PEST 评估当地法规、消费水平、文化习惯与技术基础设施。',
    tags: ['宏观环境', '战略规划', '新市场'],
  },
  {
    id: 'competitive_matrix',
    name: '竞品矩阵',
    nameEn: 'Competitive Matrix',
    category: 'market',
    stages: ['gr1', 'gr2'],
    departments: ['市场代表', 'GTM Lead'],
    description: '以功能维度或价值维度为轴，将竞品和自身产品进行多维度横向对比，直观识别差距与机会。',
    howToUse: '在产品定义阶段使用，帮助团队明确产品的差异化方向和核心卖点。',
    example: '对比主要竞品在价格、功能、服务、渠道等维度的表现，找到市场空白。',
    tags: ['竞争分析', '差异化', '产品定位'],
  },

  // ── 用户研究 ──────────────────────────────────────────────
  {
    id: 'persona',
    name: '用户画像',
    nameEn: 'User Persona',
    category: 'user',
    stages: ['gr1', 'gr2'],
    departments: ['市场代表', 'CRM / 用户运营'],
    description: '基于调研数据构建虚构但具有代表性的目标用户原型，包含用户的人口属性、行为特征、痛点与目标，帮助团队对齐"为谁设计"。',
    howToUse: '在需求定义阶段使用，确保产品功能和营销信息针对真实目标用户群。',
    example: '为智能音箱产品构建"都市职场妈妈"画像，明确她的使用场景与核心诉求。',
    tags: ['用户研究', '需求定义', '目标用户'],
  },
  {
    id: 'kano',
    name: '卡诺模型',
    nameEn: 'Kano Model',
    category: 'user',
    stages: ['gr1', 'gr2'],
    departments: ['市场代表', 'LPDT'],
    description: '将产品功能按用户满意度影响分为基本型、期望型、兴奋型三类，帮助团队优先开发高价值功能，避免在基础功能上过度投入。',
    howToUse: '在产品功能规划阶段使用，通过问卷调研收集用户对各功能的态度数据。',
    example: '调研用户对新功能的态度，发现"语音控制"是兴奋型功能，可作为差异化卖点。',
    tags: ['功能优先级', '需求分析', '用户满意度'],
  },
  {
    id: 'jtbd',
    name: 'Jobs-to-be-Done',
    nameEn: 'Jobs-to-be-Done (JTBD)',
    category: 'user',
    stages: ['gr1'],
    departments: ['市场代表', 'LPDT'],
    description: '关注用户"雇用"产品去完成的任务，而非产品本身的特性。通过理解用户真正想完成的目标，发现产品机会。',
    howToUse: '在产品概念阶段使用深度访谈，挖掘用户在特定情境下的真实需求动机。',
    example: '"人们买的不是钻头，而是墙上的洞"——用户购买智能音箱是为了解放双手，而非音乐本身。',
    tags: ['用户洞察', '需求挖掘', '产品机会'],
  },
  {
    id: 'journey_map',
    name: '用户旅程地图',
    nameEn: 'User Journey Map',
    category: 'user',
    stages: ['gr1', 'gr2'],
    departments: ['市场代表', 'CRM / 用户运营', '服务代表'],
    description: '以时间轴形式呈现用户与产品/品牌交互的完整过程，包括每个阶段的行为、情绪、痛点和机会点。',
    howToUse: '在产品设计和 GTM 规划阶段使用，帮助团队识别用户体验的关键触点和改善机会。',
    example: '梳理用户从"发现产品广告"到"购买使用"再到"寻求售后"的完整旅程，找出体验断层。',
    tags: ['用户体验', '触点分析', 'GTM规划'],
  },
  {
    id: 'empathy_map',
    name: '同理心地图',
    nameEn: 'Empathy Map',
    category: 'user',
    stages: ['gr1'],
    departments: ['市场代表'],
    description: '从"想什么/说什么/做什么/感受什么"四个维度深入理解目标用户的内心世界，是用户画像的补充工具。',
    howToUse: '在用户研究阶段配合访谈和观察使用，帮助团队建立对用户的感性认知。',
    example: '访谈后填写同理心地图，发现用户对产品价格"说可以接受"但内心仍有顾虑。',
    tags: ['用户研究', '设计思维', '定性研究'],
  },

  // ── 产品策略 ──────────────────────────────────────────────
  {
    id: 'value_proposition',
    name: '价值主张画布',
    nameEn: 'Value Proposition Canvas',
    category: 'product',
    stages: ['gr1', 'gr2'],
    departments: ['LPDT', '市场代表'],
    description: '将产品提供的价值（价值地图）与用户的需求和痛点（用户画布）进行匹配，确保产品真正解决用户问题。',
    howToUse: '在产品定义阶段使用，明确产品核心价值主张和差异化定位。',
    example: '将产品功能与用户"工作"和"痛点"对应，确认哪些功能真正创造用户价值。',
    tags: ['产品定义', '价值主张', '用户匹配'],
  },
  {
    id: 'bmc',
    name: '商业模式画布',
    nameEn: 'Business Model Canvas',
    category: 'product',
    stages: ['gr1'],
    departments: ['LPDT', '财务代表', 'GTM Lead'],
    description: '用九个模块（客户细分、价值主张、渠道通路、客户关系、收入来源、核心资源、关键业务、重要合作、成本结构）描述和设计商业模式。',
    howToUse: '在产品立项阶段使用，帮助团队快速对齐商业逻辑和盈利路径。',
    example: '用商业模式画布梳理新产品的盈利模式，明确直销 vs 渠道分销的收入结构。',
    tags: ['商业模式', '战略规划', '立项'],
  },
  {
    id: 'bcg',
    name: 'BCG 矩阵',
    nameEn: 'BCG Matrix',
    category: 'product',
    stages: ['gr5a', 'gr6'],
    departments: ['LPDT', '财务代表'],
    description: '根据市场增长率和相对市场份额，将产品或业务单元分为明星、问题、现金牛、瘦狗四类，指导资源分配决策。',
    howToUse: '在产品组合管理阶段使用，帮助决策哪些产品需要加大投入、维持或退出。',
    example: '对在售产品线进行 BCG 分析，识别"现金牛"产品以支撑新品研发投入。',
    tags: ['产品组合', '资源分配', '生命周期'],
  },
  {
    id: 'ansoff',
    name: 'Ansoff 矩阵',
    nameEn: 'Ansoff Matrix',
    category: 'product',
    stages: ['gr1'],
    departments: ['LPDT', 'GTM Lead'],
    description: '通过产品（新/现有）× 市场（新/现有）四象限分析，识别增长机会：市场渗透、市场开发、产品开发、多元化。',
    howToUse: '在制定增长战略时使用，帮助团队评估不同增长路径的风险与机会。',
    example: '评估是否进入新地区市场（市场开发）还是为现有用户推出新品（产品开发）。',
    tags: ['增长策略', '市场扩张', '战略规划'],
  },
  {
    id: 'roadmap',
    name: '产品路线图',
    nameEn: 'Product Roadmap',
    category: 'product',
    stages: ['gr2', 'gr3', 'gr5a'],
    departments: ['LPDT', 'PDT / PMO'],
    description: '以时间轴形式呈现产品功能迭代计划，对齐内部团队和外部利益相关方对产品发展方向的预期。',
    howToUse: '在产品规划阶段制定，贯穿整个产品生命周期持续更新维护。',
    example: '制定季度迭代路线图，明确 Q1 核心功能、Q2 体验优化、Q3 新品发布节奏。',
    tags: ['产品规划', '迭代管理', '对齐工具'],
  },

  // ── GTM & 营销 ──────────────────────────────────────────────
  {
    id: 'fabe',
    name: 'FABE 模型',
    nameEn: 'FABE Model',
    category: 'gtm',
    stages: ['gr3', 'gr4'],
    departments: ['市场代表', '内容与创意'],
    description: '从特征 (Feature)、优势 (Advantage)、利益 (Benefit)、证据 (Evidence) 四个层次提炼和表达产品卖点，是销售和内容创作的核心框架。',
    howToUse: '在产品文案和销售培训阶段使用，确保卖点表达以用户利益为导向而非单纯罗列功能。',
    example: '耳机产品：Feature（40dB 主动降噪）→ Advantage（隔绝环境噪音）→ Benefit（专注工作，效率翻倍）→ Evidence（XXX 实验室认证）。',
    tags: ['卖点提炼', '内容创作', '销售工具'],
  },
  {
    id: 'stp',
    name: 'STP 策略',
    nameEn: 'STP (Segmentation, Targeting, Positioning)',
    category: 'gtm',
    stages: ['gr1', 'gr2'],
    departments: ['市场代表', 'GTM Lead'],
    description: '通过市场细分 (Segmentation)、目标市场选择 (Targeting)、定位 (Positioning) 三步，确定"我们服务谁"和"我们是什么"。',
    howToUse: '在品牌定位和 GTM 规划阶段使用，是营销战略的基础框架。',
    example: '将智能音箱市场细分为家庭娱乐、办公效率、老年陪伴等用途，选择办公效率作为主攻目标市场。',
    tags: ['市场定位', '目标市场', 'GTM基础'],
  },
  {
    id: '4p',
    name: '4P 营销组合',
    nameEn: 'Marketing Mix (4P)',
    category: 'gtm',
    stages: ['gr2', 'gr4'],
    departments: ['GTM Lead', '市场代表'],
    description: '从产品 (Product)、价格 (Price)、渠道 (Place)、推广 (Promotion) 四个维度制定营销策略，确保各要素协同配合。',
    howToUse: '在 GTM 规划阶段使用，帮助团队全面覆盖营销决策点并确保策略一致性。',
    example: '上市前用 4P 检查：产品是否就绪、定价是否合理、渠道是否铺货到位、推广计划是否落地。',
    tags: ['GTM规划', '营销策略', '上市准备'],
  },
  {
    id: 'brand_pyramid',
    name: '品牌金字塔',
    nameEn: 'Brand Pyramid',
    category: 'gtm',
    stages: ['gr1', 'gr2'],
    departments: ['营销代表', 'GTM Lead'],
    description: '从品牌属性、功能利益、情感利益、用户形象、品牌个性五个层次构建品牌价值体系，指导品牌内容创作和用户沟通。',
    howToUse: '在品牌建设初期使用，为后续所有营销内容和传播策略提供方向指南。',
    example: '为新品牌定义：属性（高性价比产品）→ 情感（让普通人也能享受科技）→ 个性（平易近人、创新务实）。',
    tags: ['品牌建设', '品牌战略', '内容方向'],
  },
  {
    id: 'ab_test',
    name: 'A/B 测试框架',
    nameEn: 'A/B Testing',
    category: 'gtm',
    stages: ['gr3', 'gr5', 'gr5a'],
    departments: ['营销代表', 'CRM / 用户运营', '渠道/电商代表'],
    description: '通过对比两个版本的营销素材、页面或策略，以数据驱动方式优化转化效果，减少主观决策风险。',
    howToUse: '在营销优化和电商运营阶段持续使用，建立"假设→测试→验证→迭代"的数字化营销闭环。',
    example: '测试两版详情页主图：A 版突出产品外观，B 版突出使用场景，通过点击率和转化率决定最优版本。',
    tags: ['数据驱动', '营销优化', '电商运营'],
  },

  // ── 项目管理 ──────────────────────────────────────────────
  {
    id: 'raci',
    name: 'RACI 矩阵',
    nameEn: 'RACI Matrix',
    category: 'pm',
    stages: ['gr1', 'gr2'],
    departments: ['MO 营运运作', 'PDT / PMO'],
    description: '明确项目中每个任务的执行者 (R)、决策者 (A)、咨询者 (C)、知会者 (I)，消除职责模糊和重复工作。',
    howToUse: '在项目启动阶段建立，明确每个交付物由谁执行、谁拍板，避免"多头管理"或"无人负责"。',
    example: '用 RACI 厘清 GR 评审中各角色的职责：PMO 执行准备，MO 协调审批，PDT Lead 负责最终拍板。',
    tags: ['责任分工', '项目启动', '跨部门协作'],
  },
  {
    id: 'risk_matrix',
    name: '风险矩阵',
    nameEn: 'Risk Matrix',
    category: 'pm',
    stages: ['gr1', 'gr2', 'gr3'],
    departments: ['MO 营运运作', 'PDT / PMO'],
    description: '按发生概率和影响程度对项目风险进行二维评估和可视化，帮助团队优先处理高优先级风险。',
    howToUse: '在项目规划阶段建立风险登记表，并在每个里程碑节点更新风险状态。',
    example: '识别"关键物料供应商断货"为高概率高影响风险，提前制定备选供应商方案。',
    tags: ['风险管理', '项目规划', '里程碑'],
  },
  {
    id: 'wbs',
    name: 'WBS 工作分解',
    nameEn: 'Work Breakdown Structure',
    category: 'pm',
    stages: ['gr1', 'gr2'],
    departments: ['PDT / PMO'],
    description: '将项目目标逐层分解为可执行的工作包，确保所有任务可被分配、追踪和管理，是项目计划的基础结构。',
    howToUse: '在项目规划阶段使用，为甘特图排期、资源分配和进度追踪提供结构基础。',
    example: '将"完成产品上市"分解为市场准备、供应链准备、渠道准备等一级任务，再进一步细分到具体工作包。',
    tags: ['项目规划', '任务分解', '进度管理'],
  },
  {
    id: 'okr',
    name: 'OKR 目标框架',
    nameEn: 'Objectives and Key Results',
    category: 'pm',
    stages: ['gr1', 'gr5', 'gr5a'],
    departments: ['GTM Lead', 'LPDT', 'MO 营运运作'],
    description: '通过设定清晰的目标 (Objective) 和可量化的关键结果 (Key Results)，对齐团队方向并追踪进展。',
    howToUse: '在季度或项目启动时使用，确保团队在执行层面对齐战略目标。',
    example: 'O：成功完成新品上市；KR1：首月销售额达到 500 万；KR2：NPS ≥ 60；KR3：媒体曝光量 ≥ 1亿次。',
    tags: ['目标管理', '团队对齐', '绩效追踪'],
  },

  // ── 财务分析 ──────────────────────────────────────────────
  {
    id: 'roi',
    name: 'ROI 分析',
    nameEn: 'Return on Investment Analysis',
    category: 'finance',
    stages: ['gr1', 'gr2'],
    departments: ['财务代表', 'LPDT'],
    description: '通过计算投资回报率评估项目或产品的财务可行性，帮助决策者判断资源投入的合理性。',
    howToUse: '在立项和商业计划阶段使用，为高层决策提供财务依据。',
    example: '计算新品研发投入 1000 万，预计三年回收 3000 万，ROI = 200%，支撑立项决策。',
    tags: ['财务决策', '立项评估', '投资分析'],
  },
  {
    id: 'pl_model',
    name: 'P&L 模型',
    nameEn: 'Profit & Loss Model',
    category: 'finance',
    stages: ['gr1', 'gr4', 'gr5'],
    departments: ['财务代表'],
    description: '预测产品在生命周期内的收入、成本和利润结构，是产品商业决策的核心财务工具。',
    howToUse: '在产品规划和定价阶段建立，上市后持续更新实绩数据与预测对比。',
    example: '在上市前构建三年 P&L 预测，明确盈亏平衡点所需的销量目标。',
    tags: ['利润分析', '定价决策', '财务规划'],
  },
  {
    id: 'bom_cost',
    name: 'BOM 成本分析',
    nameEn: 'Bill of Materials Cost Analysis',
    category: 'finance',
    stages: ['gr1', 'gr2', 'gr3'],
    departments: ['财务代表', '采购代表'],
    description: '通过逐项分析产品物料清单的成本构成，识别降本机会，确保产品达到目标利润率。',
    howToUse: '在产品开发阶段持续使用，配合采购和制造团队共同优化成本结构。',
    example: '分析 BOM 发现某模块占总成本 30%，通过国产化替代降低 15% 成本。',
    tags: ['成本管理', '供应链', '降本增效'],
  },

  // ── 用户增长 ──────────────────────────────────────────────
  {
    id: 'aarrr',
    name: 'AARRR 海盗模型',
    nameEn: 'AARRR (Pirate Metrics)',
    category: 'growth',
    stages: ['gr5', 'gr5a'],
    departments: ['营销代表', 'CRM / 用户运营'],
    description: '从获取 (Acquisition)、激活 (Activation)、留存 (Retention)、收入 (Revenue)、推荐 (Referral) 五个阶段分析用户增长漏斗，识别增长瓶颈。',
    howToUse: '在产品上市后使用，持续分析各阶段的转化率，找到增长的最大杠杆点。',
    example: '发现激活率仅 30%，重点优化首次使用体验和引导流程，而非继续扩大获客投入。',
    tags: ['用户增长', '漏斗分析', '增长策略'],
  },
  {
    id: 'rfm',
    name: 'RFM 模型',
    nameEn: 'RFM Model',
    category: 'growth',
    stages: ['gr5a'],
    departments: ['CRM / 用户运营', '销售代表'],
    description: '从最近一次消费时间 (Recency)、消费频率 (Frequency)、消费金额 (Monetary) 三个维度对用户进行价值分层，支撑精准运营。',
    howToUse: '在产品稳定运营阶段使用，针对高价值用户制定留存策略，对低活跃用户制定激活方案。',
    example: '识别"高频高金额但近期未购"的流失风险用户，触发专属召回优惠推送。',
    tags: ['用户分层', '精准运营', 'CRM'],
  },
  {
    id: 'nps',
    name: 'NPS 净推荐值',
    nameEn: 'Net Promoter Score',
    category: 'growth',
    stages: ['gr5', 'gr5a'],
    departments: ['服务代表', 'CRM / 用户运营', '技术服务代表'],
    description: '通过"你有多大可能向朋友推荐我们的产品"这一问题，将用户分为推荐者、被动者、批评者，量化用户忠诚度。',
    howToUse: '在产品上市后定期（如季度）测量，追踪用户满意度趋势并识别体验改善优先项。',
    example: '新品上市三个月后 NPS = 45，重点跟进"批评者"的负面反馈，针对性优化产品体验。',
    tags: ['用户满意度', '口碑管理', '体验优化'],
  },

  // ── 质量管理 ──────────────────────────────────────────────
  {
    id: 'fmea',
    name: 'FMEA',
    nameEn: 'Failure Mode and Effects Analysis',
    category: 'quality',
    stages: ['gr1', 'gr2', 'gr3'],
    departments: ['质量代表', '制造代表'],
    description: '系统性识别产品或流程中可能的失效模式及其影响，通过风险优先级数 (RPN) 指导预防措施的制定。',
    howToUse: '在产品设计和工艺开发阶段使用，提前识别高风险失效点，减少后期质量问题。',
    example: '对电池模块进行 FMEA 分析，识别过热失效风险为最高 RPN，设计三重保护机制。',
    tags: ['质量预防', '风险识别', '可靠性'],
  },
  {
    id: 'six_sigma',
    name: '6-Sigma',
    nameEn: 'Six Sigma (DMAIC)',
    category: 'quality',
    stages: ['gr3', 'gr4', 'gr5a'],
    departments: ['质量代表', '制造代表'],
    description: '通过定义 (D)、测量 (M)、分析 (A)、改进 (I)、控制 (C) 五步方法论，系统性消除流程中的缺陷和变异，实现质量持续改善。',
    howToUse: '在量产质量改善阶段使用，适合解决有明确数据支撑的复杂质量问题。',
    example: '某工序良率仅 94%，通过 DMAIC 分析出关键控制参数，优化后良率提升至 99.2%。',
    tags: ['质量改善', '流程优化', '数据驱动'],
  },
];
